#!/usr/bin/env bash

# notify-send Announcements "I'm starting to backup your history"

NOW=$(date +"%d_%m_%Y")
FILE="history_$NOW.log"
LOCATION="$HOME/history_logs"

mkdir -p "$LOCATION"

copy_history() {
  local filename="$1"
  if [ -f "$HOME/$filename" ]; then
    cp "$HOME/$filename" "$LOCATION/${USER}_${filename}_${FILE}"
  fi
}

find -E ~ -regex '.*(zsh|bash|redis|psql|python|rediscli|guard|node_repl)(.|-|_)(history).*$' -maxdepth 1 -type f | while read -r filepath; do
  copy_history "$(basename "$filepath")"
done
