name: Run setup.sh on macOS

on:
  push:
    branches: [test-ci]
  pull_request:
    branches: [test-ci]

jobs:
  macos-setup:
    runs-on: macos-latest
    timeout-minutes: 45

    steps:
      - name: Show environment
        run: env

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Grant execute permission to setup.sh
        run: chmod +x ./setup.sh

      - name: Run setup.sh
        run: ./setup.sh